config/api_platform/screen_groups.yaml
fixtures/screen_group.yaml
migrations/Version20211005165920.php
public/api-spec-v1.yaml
src/Controller/PlaylistSlidePutController.php
src/Controller/ScreenGroupsScreensDeleteController.php
src/Controller/ScreenGroupsScreensGetController.php
src/Controller/ScreenGroupsScreensPutController.php
src/Entity/Screen.php
src/Entity/ScreenGroup.php
src/Repository/PlaylistSlideRepository.php
src/Repository/ScreenGroupRepository.php
tests/Api/ScreenGroupsTest.php

https://jira.itkdev.dk/browse/AR-680
List, relate and un-relate screens and screen groups.
No comments.

Handle screen groups on screen end-points

---

config/api_platform/playlist_screen_region.yaml
config/api_platform/playlist_slide.yaml
config/api_platform/screen.yaml
config/api_platform/screen_groups.yaml
config/api_platform/slide.yaml
public/api-spec-v1.yaml
src/Utils/Utils.php
tests/Api/PlaylistScreenRegionTest.php
tests/Api/PlaylistSlideTest.php
tests/Api/ScreenGroupsTest.php
tests/UtilsTest.php

https://jira.itkdev.dk/browse/AR-663
Ensured that all end-point follow the "dash" naming 
No screenshot.
No comment.

AR-678: Ensured end-point paths follow same pattern

---

src/Command/LoadScreenLayoutsCommand.php

No ticket
Added command to load one screen layout with one region
No screen shot

AR-543: Added command to load screen layout

---

fixtures/media.yaml
fixtures/playlist.yaml
fixtures/playlist_screen_region.yaml
fixtures/playlist_slide.yaml
fixtures/screen.yaml
fixtures/screen_group.yaml
fixtures/screen_layout.yaml
fixtures/screen_layout_region.yaml
fixtures/slide.yaml
fixtures/template.yaml
src/DataFixtures/Faker/Provider/UlidProvider.php

https://jira.itkdev.dk/browse/AR-703
Copied and altered Symfony's Ulid generator to use FakerPHP generator for random values so that it generates predictable id's.
No screenshot

AR-703: Updated Ulid provider to generate predictable id's

---

src/Command/LoadScreenLayoutsCommand.php

https://jira.itkdev.dk/browse/AR-738

AR-738: rewrote command argument

---

fixtures/slide.yaml

https://jira.itkdev.dk/browse/AR-773
Remove % from relations in fixtures to make relations predictable
No screenshot

AR-773: Removed percentages from relations in fixtures

---

src/DataTransformer/PlaylistInputDataTransformer.php

https://jira.itkdev.dk/browse/AR-611

AR-611: make it possible to remove schedule

---

config/services.yaml
src/Controller/MediaController.php
src/Entity/Media.php
src/Entity/Screen.php
src/Entity/Slide.php
src/Entity/Theme.php
src/EventListener/MediaDoctrineEventListener.php
src/EventListener/ThemeDoctrineEventListener.php
tests/Api/ThemesTest.php

https://jira.itkdev.dk/browse/AR-786
* Remove orphaned relations when slide and screen are deleted.
* Block removal of media and themes when they are connected to slides (through preRemove doctrine event)

AR-786: Changed how entities are deleted

---

config/api_platform/feed_source.yaml
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Command/CreateFeedSourceCommand.php
src/Command/GenerateUlid.php
src/Feed/FeedTypeInterface.php
src/Feed/KobaFeedType.php
src/Feed/RssFeedType.php
src/Feed/SparkleIOFeedType.php
tests/Utils/FeedServiceTest.php

https://jira.itkdev.dk/browse/AR-768
Adds SparkleIO feed source

AR-768: Adds SparkleIO feed source

---

.env
.env.test
README.md
config/packages/nelmio_cors.yaml
config/packages/security.yaml
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Api/OpenApiFactory.php
src/Controller/AuthScreenController.php
src/Service/AuthScreenService.php
tests/Api/ScreensTest.php

https://jira.itkdev.dk/browse/AR-793
Modified security to allow session based calls for oidc login

AR-793: Modified security to allow session based calls for oidc login

---

docker-compose.server.yml
infrastructure/display-api-service/etc/confd/templates/env.local.tmpl

https://jira.itkdev.dk/browse/AR-793
Adds environment variables for oidc to template

AR-793: Added oidc environment variables

---

config/api_platform/playlist_slide.yaml
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Controller/SlidePlaylistPutController.php
src/Repository/PlaylistSlideRepository.php
tests/Api/PlaylistSlideTest.php

https://jira.itkdev.dk/browse/AR-781

AR-781: add playlist to slide

---

src/Command/AddTenantCommand.php
src/Entity/Tenant.php
src/Utils/CommandInputValidator.php

https://jira.itkdev.dk/browse/AR-700
Added command to add tenants

AR-700: Added app:tenant:add command

---

README.md
src/Command/LoadScreenLayoutsCommand.php
src/Command/LoadTemplateCommand.php

https://jira.itkdev.dk/browse/AR-764
Removed setCreatedAt calls following entity change

AR-764: Removed setCreatedAt calls

---

config/packages/nelmio_cors.yaml

https://jira.itkdev.dk/browse/AR-718

AR-718: added header to nelmiocors

---

src/Command/LoadScreenLayoutsCommand.php

https://jira.itkdev.dk/browse/AR-435
Fixed command to assign tenant.

AR-435: Added layout and layout regions to tenant

---

src/Repository/PlaylistSlideRepository.php

https://jira.itkdev.dk/browse/AR-611

AR-611: moved flush outside of loop

---

config/api_platform/feed_source.yaml
config/services.yaml
fixtures/feed_source.yaml
migrations/Version20220311112355.php
migrations/Version20220311120935.php
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Command/CreateFeedSourceCommand.php
src/DataTransformer/FeedSourceInputDataTransformer.php
src/DataTransformer/FeedSourceOutputDataTransformer.php
src/Dto/FeedSource.php
src/Dto/FeedSourceInput.php
src/Entity/Tenant/FeedSource.php
src/Feed/EventDatabaseApiFeedType.php
src/Feed/FeedTypeInterface.php
src/Feed/KobaFeedType.php
src/Feed/RssFeedType.php
src/Feed/SparkleIOFeedType.php
src/Service/FeedService.php

https://jira.itkdev.dk/browse/AR-802
Changes FeedSource to be searchable by output type.
Changed feed source command to assign to tenant and require secrets to be filled.

AR-802: Added supportedFeedOutputType field to filter feed sources

---

composer.json
composer.lock
config/bundles.php
config/packages/gesdinet_jwt_refresh_token.yaml
config/packages/security.yaml
config/routes.yaml
migrations/Version20220312224517.php
public/api-spec-v1.json
public/api-spec-v1.yaml
src/OpenApi/OpenApiFactory.php
symfony.lock

https://jira.itkdev.dk/browse/AR-800
Added and configured `gesdinet/jwt-refresh-token-bundle`

AR-800: Added refresh tokens

---

config/api_platform/screen_groups.yaml
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Filter/PublishedFilter.php

Add sort on created at to groups
Fix filter so null values return true

AR-611: null values means published

---

config/services.yaml
src/Entity/Tenant/Feed.php
src/Entity/Tenant/FeedSource.php
src/EventListener/FeedDoctrineEventListener.php
src/EventListener/FeedSourceDoctrineEventListener.php
src/Feed/KobaFeedType.php

https://jira.itkdev.dk/browse/AR-806
Remove feed cache entry when feed or feed source is updated or removed.

AR-806: Remove feed cache on Feed change

---

.env
config/packages/gesdinet_jwt_refresh_token.yaml
config/services.yaml
src/Security/ScreenAuthenticator.php

https://jira.itkdev.dk/browse/AR-816
Added refresh_token to screen authentication output

AR-816: Added refresh_token to screen authentication output

---

migrations/Version20220405093535.php
src/Command/LoadScreenLayoutsCommand.php
src/Command/RemoveScreenLayoutCommand.php
src/Dto/ScreenLayoutRegions.php
src/Entity/ScreenLayoutRegions.php

https://jira.itkdev.dk/browse/AR-648
Add support touch regions.
Changed load screen layout command.
Added remove screen layout command.

AR-648: Added screen region type

---

src/Command/RemoveFeedSourceCommand.php
src/Entity/Tenant/Feed.php
src/Entity/Tenant/Slide.php

https://jira.itkdev.dk/browse/AR-821
Added remove feed source command
Added bidirection to feed slide connection

AR-821: Added remove feed source command

---

migrations/Version20220427060919.php
public/api-spec-v1.json
public/api-spec-v1.yaml
src/DataTransformer/ScreenInputDataTransformer.php
src/DataTransformer/ScreenOutputDataTransformer.php
src/Dto/Screen.php
src/Dto/ScreenInput.php
src/Entity/Tenant/Screen.php

https://jira.itkdev.dk/browse/AR-723
Adds field to enable color scheme change for screens.

AR-723: Added enableColorSchemeChange field to screen

---

infrastructure/display-api-service/etc/confd/templates/env.local.tmpl

https://jira.itkdev.dk/browse/AR-797
Added missing values

AR-797: Updated infrastructure env template with missing values

---

src/DataProvider/ScreenScreenGroupsCollectionDataProvider.php
src/Repository/ScreenRepository.php

https://jira.itkdev.dk/browse/AR-826

AR-826: switched screen to screengroup

---

migrations/Version20220510124916.php
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Command/ConfigureTenantCommand.php
src/Entity/Tenant.php
src/Security/ScreenAuthenticator.php

https://jira.itkdev.dk/browse/AR-835
Adds fallbackImageUrl to tenant. 
Adds command to configure tenant.

AR-835: Added fallbackImageUrl and command to add it to tenant

---

migrations/Version20220706144147.php
public/api-spec-v1.json
public/api-spec-v1.yaml
src/DataTransformer/ThemeInputDataTransformer.php
src/DataTransformer/ThemeOutputDataTransformer.php
src/Dto/Theme.php
src/Dto/ThemeInput.php
src/Entity/Tenant/Theme.php

https://jira.itkdev.dk/browse/SUPP0RT-554
I have added the logo as a media to themes

SUPP0RT-554: add logo to theme

---

fixtures/screen.yaml
migrations/Version20220831111531.php
public/api-spec-v1.json
public/api-spec-v1.yaml
src/DataTransformer/ScreenInputDataTransformer.php
src/DataTransformer/ScreenOutputDataTransformer.php
src/Dto/Screen.php
src/Dto/ScreenInput.php
src/Entity/Tenant/Screen.php
tests/Api/ScreensTest.php

https://jira.itkdev.dk/browse/AR-860
remove screen width / height. add resolution/orientation.

AR-859: add resolution and orientation to screen

---

public/api-spec-v1.json
public/api-spec-v1.yaml
src/Feed/KobaFeedType.php

https://jira.itkdev.dk/browse/AR-867
Changes to KOBA feed source:
- Changed naming in resource options
- Sorted options

AR-867: Changed naming in resource options and added sorting

---

README.md
fixtures/media.yaml
fixtures/slide.yaml
src/Entity/Tenant/Media.php
src/Filter/TenantExtension.php
src/Service/MediaUploadTenantDirectoryNamer.php
tests/Api/MediaTest.php

https://jira.itkdev.dk/browse/AR-864
Fixed path for shared Media

AR-864: Fix path for shared Media

---

src/Command/LoadScreenLayoutsCommand.php

https://jira.itkdev.dk/browse/AR-871
Changes load screen layout command to allow updating existing layouts.

AR-871: Changed command to updating screen layouts

---

.docker/vhost.conf
docker-compose.yml
infrastructure/display-api-service/Dockerfile
infrastructure/display-api-service/docker-entrypoint.sh
infrastructure/display-api-service/etc/confd/conf.d/env.local.toml
infrastructure/nginx/Dockerfile
infrastructure/nginx/docker-entrypoint.sh
infrastructure/nginx/etc/confd/templates/default.conf.tmpl
infrastructure/nginx/etc/confd/templates/nginx.conf.tmpl
infrastructure/run.sh

https://jira.itkdev.dk/browse/AR-875
Updated docker setup to match new itkdev base setup
N/A
N/A

Docker update

---

src/Feed/KobaFeedType.php

https://jira.itkdev.dk/browse/SUPP0RT-753
* Changed error handling to not always return empty array even though it is only one resource that reports error.
* Added error logging.

SUPPORT-753: Added better error handling for koba getData calls

---

.github/workflows/docker_build_develop.yml
.github/workflows/docker_build_tag.yml
.github/workflows/php_upgrade.yaml
.github/workflows/pr.yaml
README.md
fixtures/playlist_screen_region.yaml
fixtures/screen.yaml
fixtures/screen_layout.yaml
fixtures/screen_layout_region.yaml
fixtures/slide.yaml
fixtures/template.yaml
fixtures/theme.yaml
fixtures/user.yaml
fixtures/user_role_tenant.yaml
migrations/Version20221128121323.php
public/api-spec-v1.json
public/api-spec-v1.yaml
src/DataFixtures/Faker/Provider/ResourceProvider.php
src/Entity/Tenant/PlaylistScreenRegion.php
src/OpenApi/OpenApiFactory.php
tests/Api/LayoutsTest.php
tests/Api/ScreensTest.php
tests/Api/SlidesTest.php
tests/Api/TemplatesTest.php
tests/Api/ThemesTest.php
tests/Security/JWSProviderDecoratorTest.php

https://jira.itkdev.dk/browse/AR-877
Not really the right ticket, as this did not have an assignment, but I did it anyway. 

Ar-877: update fixtures

---

.env
config/packages/cache.yaml
config/services.yaml
src/Security/JWSProviderDecorator.php
src/Security/ScreenAuthenticator.php
src/Utils/ValidationUtils.php
tests/Security/JWSProviderDecoratorTest.php

https://jira.itkdev.dk/browse/AR-890
Added config option for setting token TTL for screen users

AR-890: Added config option for setting token TTL for screen users

---

composer.lock
config/packages/gesdinet_jwt_refresh_token.yaml

https://jira.itkdev.dk/browse/AR-890
Added `ttl_update: true` config option for jwt refresh bundle
Added `refresh_token_expiration` key to respone body
```
{
"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzI3Nzk2MTYsImV4cCI6MTY3Mjc4MzIxNiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiam9obkBleGFtcGxlLmNvbSJ9.2M81JQSS_p0xc-eZA5vIw_4LWxInGQoHN8_zViD25sy6LIY4S4in4cV9A9XBSIkz6Ypu2ZRIv0liIfZAUpxk-R_0aBUoQEvaF-0_lP7J9lDNKSBnlAgKtGnFxe5QdYXM4tB5DkaLq08RjCuHLrSjOuAwV0s5Bl0zRs0h8Kbrm0ga4icG_kpzw82zOMYdqc8v457q9JoMT3IW8XSkswPwsiv1rMDWcfYHjRxV4LnFNYzycvkTUnsWrogBdWqPwP9j2CGXtsK9DPqYLZGdqN9TUE4RQA4ys5UGVj8yNYfm8Z7jLItm4yeTLlsPvOlONDb7FprGDJ5nMf2exyRMa9YcvA",
"refresh_token": "3bed844b627920fee4f06c073775506f186a2942197c0ab21b2936d2ac58c4ab5178bf3d5acdac559b18f9e3bc735c586484340c3c4f08ef81f …
```

AR-890: Added config option for refresh token ttl update

---

composer.json
composer.lock
public/api-spec-v1.json
public/api-spec-v1.yaml
tests/Api/FeedSourceTest.php
tests/Api/LayoutsTest.php
tests/Api/MediaTest.php
tests/Api/PlaylistsTest.php
tests/Api/ScreenGroupsTest.php
tests/Api/ScreensTest.php
tests/Api/SlidesTest.php
tests/Api/TemplatesTest.php
tests/Api/ThemesTest.php

https://jira.itkdev.dk/browse/AR-890
Upgrading to `2.7` introduced a change in serialization. Locking to `2.6.*`

AR-890: Locking api-platform to 2.6.* for compatibility reasons

---

.github/workflows/pr.yaml
CHANGELOG.md

https://jira.itkdev.dk/browse/AR-891
* Added changelog.
* Added github action to enforce that PRs should always include an update of the changelog.

AR-891: Added changelog and github action

---

CHANGELOG.md
config/packages/gesdinet_jwt_refresh_token.yaml
src/Entity/RefreshToken.php

https://jira.itkdev.dk/browse/AR-897
Added `RefreshToken` entity and config to fix migrations error
N/A

AR-897: Added RefreshToken entity and configuration

---

CHANGELOG.md
src/Entity/AbstractBaseEntity.php
src/Entity/RefreshToken.php
src/Entity/ScreenLayout.php
src/Entity/ScreenLayoutRegions.php
src/Entity/Template.php
src/Entity/Tenant.php
src/Entity/Tenant/AbstractTenantScopedEntity.php
src/Entity/Tenant/Feed.php
src/Entity/Tenant/FeedSource.php
src/Entity/Tenant/Media.php
src/Entity/Tenant/Playlist.php
src/Entity/Tenant/PlaylistScreenRegion.php
src/Entity/Tenant/PlaylistSlide.php
src/Entity/Tenant/Schedule.php
src/Entity/Tenant/Screen.php
src/Entity/Tenant/ScreenCampaign.php
src/Entity/Tenant/ScreenGroupCampaign.php
src/Entity/Tenant/Slide.php
src/Entity/Tenant/Theme.php
src/Entity/UserRoleTenant.php

No ticket
The code style rules seems to have been updated causing the code style check to fail. Have run `vendor/bin/php-cs-fixer fix` to update files.
N/A

Applied updated coding standards

---

.github/workflows/docker_build_develop.yml
.github/workflows/docker_build_tag.yml
.github/workflows/php_upgrade.yaml
.github/workflows/pr.yaml
CHANGELOG.md

No ticket
- Update github actions to latest versions
N/A

Update to latest github actions

---

CHANGELOG.md
src/Command/ConfigureTenantCommand.php
src/Entity/Tenant.php

https://jira.itkdev.dk/browse/AR-943
Fixed Tenant and command to allow for empty fallbackImageUrl

AR-943: Fixed Tenant and command to allow for empty fallbackImageUrl

---

CHANGELOG.md
docker-compose.yml

https://jira.itkdev.dk/browse/AR-951
Readded redis to docker-compose

AR-951: Readded redis to docker-compose

---

CHANGELOG.md
src/Entity/Tenant/Media.php

n/a jira link not viewable people outside itk. 
The customer wants to be able to upload gifs.
n/a 

SUPP0RT-995: gif accepted mine type

---

CHANGELOG.md
src/Feed/EventDatabaseApiFeedType.php

https://jira.itkdev.dk/browse/DISPLAY-947
Updates `EventDatabase` query to ensure events that are still on-going are found.
N/A
N/A

DISPLAY-947: Updated EventDatabase query

---

infrastructure/nginx/docker-entrypoint.sh

ITKDev: Fixed nginx entry script

---

.github/workflows/github_build_release.yml
CHANGELOG.md

N/A 
Fix permissions in create release github action

DISPLAY-986: Fix permissions in create release github action

---

CHANGELOG.md
src/Command/User/AddUserCommand.php

https://jira.itkdev.dk/browse/SUPP0RT-1071
Fix question input on create user command

DISPLAY-986: Fix question input on create user command

---

CHANGELOG.md
src/DataProvider/FeedDataProvider.php

https://jira.itkdev.dk/browse/DISPLAY-1016
Fixed 500 feed data error.

DISPLAY-1016: Fixed 500 feed data error

---

CHANGELOG.md
src/Command/Feed/ListFeedSourceCommand.php
src/Command/Feed/RemoveFeedSourceCommand.php

https://jira.itkdev.dk/browse/SUPP0RT-1163
Moved list out of remove feed source command

SUPPORT-1163: Moved list out of remove feed source command

---

CHANGELOG.md
README.md
composer.json
composer.lock
config/packages/itkdev_openid_connect.yaml
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Command/User/AddUserCommand.php
src/Controller/AuthOidcController.php
src/Entity/Tenant/Media.php
src/Feed/KobaFeedType.php
src/Filter/SharedWithMe.php
src/OpenApi/OpenApiFactory.php
src/Security/AzureOidcAuthenticator.php
src/Serializer/RelationNormalizer.php
tests/Api/LayoutsTest.php
tests/Api/MediaTest.php
tests/Api/SlidesTest.php
tests/Api/TemplatesTest.php

Code authorization flow

---

CHANGELOG.md
src/DataProvider/FeedDataProvider.php
src/Service/FeedService.php

https://jira.itkdev.dk/browse/DISPLAY-1019
Removed references to non-existing exception

DISPLAY-1019: Removed references to non-existing exception

---

CHANGELOG.md
composer.json
composer.lock

https://jira.itkdev.dk/browse/DISPLAY-1030
Updates Symfony development packages.

Updated Symfony development packages

---

CHANGELOG.md
config/api_platform/playlist_slide.yaml
public/api-spec-v1.json
public/api-spec-v1.yaml
tests/Api/PlaylistSlideTest.php

https://jira.itkdev.dk/browse/DISPLAY-1030
Fixes collection operation.

Fixed slide playlists collection operation

---

.yamllint.yaml
CHANGELOG.md
README.md
config/api_platform/feed.yaml
config/api_platform/feed_source.yaml
config/api_platform/layout.yaml
config/api_platform/media.yaml
config/api_platform/playlist.yaml
config/api_platform/playlist_screen_region.yaml
config/api_platform/playlist_slide.yaml
config/api_platform/screen.yaml
config/api_platform/screen_campaign.yaml
config/api_platform/screen_groups.yaml
config/api_platform/screen_groups_campaign.yaml
config/api_platform/screen_layout_regions.yaml
config/api_platform/slide.yaml
config/api_platform/template.yaml
config/api_platform/tenant.yaml
config/api_platform/theme.yaml

https://jira.itkdev.dk/browse/DISPLAY-1030
Lints YAML API definitions to easy transition to API Platform 3 (by making YAML comparisions easier).

Linted YAML

---

CHANGELOG.md
config/api_platform/screen_campaign.yaml
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Dto/Playlist.php
src/Dto/ScreenCampaign.php
src/State/ScreenCampaignProvider.php

https://jira.itkdev.dk/browse/DISPLAY-1088
Expands `campaign` in the `/v1/screens/{id}/campaigns` endpoint.
Updated automated tests for this are still not completed.

Expanded campaign

---

CHANGELOG.md
config/api_platform/theme.yaml
fixtures/theme.yaml
migrations/Version20240110091802.php
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Dto/Media.php
src/Dto/Slide.php
src/Dto/Theme.php
src/Entity/Tenant/Theme.php
src/EventListener/RelationsModifiedAtListener.php
src/State/PlaylistSlideProvider.php
src/State/SlideProvider.php
src/State/ThemeProvider.php
tests/EventListener/RelationsModifiedAtListenerTest.php

https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/161
Changed "Theme" api output to have "Logo" embedded to avoid 404 errors when fetching logo from other shared slide w. foreign tenant.

#161: Changed "Theme" api output to have "Logo" embedded to avoid 404 errors

---

CHANGELOG.md
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Dto/Trait/RelationsChecksumTrait.php
src/Feed/KobaFeedType.php

https://leantime.itkdev.dk/#/tickets/showTicket/369
* Added serialization groups to RelationsChecksumTrait
* Fixed deprecation warning in KobaFeedType

Added serialization groups to RelationsChecksumTrait

---

infrastructure/itkdev/display-api-service/Dockerfile

Please add a link to the ticket being addressed by this change.
Added `COMPOSER_ALLOW_SUPERUSER=1 ` to allow image build to succed

#534 - Fix itkdev docker image build

---

CHANGELOG.md
psalm-baseline.xml
src/Security/AzureOidcAuthenticator.php

Please add a link to the ticket being addressed by this change.

#534 - Add logging for OIDC errors

---

.github/workflows/php_upgrade.yaml
.github/workflows/pr.yaml
CHANGELOG.md
composer.json
composer.lock
config/api_platform/feed.yaml
config/api_platform/feed_source.yaml
config/services.yaml
psalm-baseline.xml
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Controller/FeedGetDataController.php
src/Controller/UserActivateController.php
src/Controller/UserRefreshCodeController.php
src/DataFixtures/Loader/DoctrineOrmLoaderDecorator.php
src/Dto/Slide.php
src/Entity/Tenant/Playlist.php
src/Entity/Tenant/Screen.php
src/Security/Voter/UserVoter.php
src/Service/UserService.php
src/State/FeedProvider.php
src/Utils/Roles.php
tests/Api/UserTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/367
* Fixed issues with feed following api platform upgrade

Fixed issues with feed following api platform upgrade

---

CHANGELOG.md
src/Repository/PlaylistSlideRepository.php
tests/Api/PlaylistSlideTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/366
Fixed transaction issue with PlaylistSlide

366: Fixed transaction issue with PlaylistSlide

---

CHANGELOG.md
README.md
tests/Api/PlaylistsTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/872
* Updates test run documentation.
* Adds test for `rrule` in playlist.

872: Cleaned up test run documentation

---

CHANGELOG.md
src/Repository/PlaylistSlideRepository.php

https://leantime.itkdev.dk/#/tickets/showTicket/1021
Fixed issue when assigning weight to slides in playlist.

Fixed playlist slide weight

---

CHANGELOG.md
src/Controller/ApiV1RedirectController.php
tests/Controller/ApiV1RedirectControllerTest.php

https://leantime.itkdev.dk/dashboard/show#/tickets/showTicket/1137
Add /v1 - /v2 redirect controller 

1137 - Add /v1 - /v2 redirect controller

---

CHANGELOG.md
src/Controller/ApiV1RedirectController.php
src/Entity/Interfaces/UserInterface.php
src/Entity/ScreenUser.php
src/Entity/User.php
src/EventListener/BlameableListener.php

https://leantime.itkdev.dk/#/tickets/showTicket/398
Fixed ScreenUser blamable identifier

Fixed ScreenUser blamable identifier

---

CHANGELOG.md
src/State/ThemeProcessor.php

https://leantime.itkdev.dk/#/tickets/showTicket/398
Changed theme->addLogo() to theme->setLogo()

398: Changed theme->addLogo() to theme->setLogo()

---

CHANGELOG.md
config/packages/nelmio_cors.yaml
config/packages/security.yaml
psalm-baseline.xml
src/Controller/ApiV1RedirectController.php
tests/Controller/ApiV1RedirectControllerTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/1190
Redirect post requests to v2

Redirect post requests to v2

---

CHANGELOG.md
README.md

https://leantime.itkdev.dk/#/tickets/showTicket/1127
Updated oidc internal documentation.

1127: Updated oidc internal documentation

---

CHANGELOG.md
infrastructure/itkdev/nginx/etc/confd/templates/nginx.conf.tmpl
infrastructure/os2display/nginx/etc/confd/templates/nginx.conf.tmpl

https://leantime.itkdev.dk/tickets/showKanban#/tickets/showTicket/1185
Ensure real IP is logged when behind proxy.
N/A
N/A

1185: Ensured real ip is logged in nginx

---

CHANGELOG.md
composer.json
fixtures/feed.yaml
fixtures/feed_source.yaml
fixtures/slide.yaml
fixtures/template.yaml
src/Feed/NotifiedFeedType.php
tests/Api/FeedSourceTest.php
tests/Api/SlidesTest.php
tests/Api/TemplatesTest.php
tests/Feed/NotifiedFeedTypeData.php
tests/Feed/NotifiedFeedTypeTest.php
tests/Utils/FeedServiceTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/1203
* Adds support for Notified feed as replacement for SparkleIO feed.
* Deprecated SparkleIOFeedType

Adds support for NotifiedFeedType as replacement for SparkleIOFeedType.

---

.github/workflows/php_upgrade.yaml
.github/workflows/pr.yaml
CHANGELOG.md
composer.json
src/Feed/NotifiedFeedType.php
tests/Feed/NotifiedFeedTypeTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/1203
Removed feed items from Notified where image returns 403.

1203: Removed 403 images from feed

---

CHANGELOG.md

https://leantime.itkdev.dk/dashboard/show#/tickets/showTicket/2773
Release 2.1.0

2773: Release 2.1.0

---

CHANGELOG.md
composer.lock

Please add a link to the ticket being addressed by this change.

2773: Update composer dependencies to fix redis error

---

CHANGELOG.md

https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=2773#/tickets/showTicket/2773
Release 2.1.2

2773: Release 2.1.2

---

CHANGELOG.md

https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=2773#/tickets/showTicket/2773
Release 2.1.3

2773: Release 2.1.3

---

CHANGELOG.md
composer.json
fixtures/feed.yaml
fixtures/feed_source.yaml
fixtures/playlist.yaml
fixtures/playlist_screen_region.yaml
fixtures/playlist_slide.yaml
fixtures/screen.yaml
fixtures/screen_campaign.yaml
fixtures/slide.yaml
tests/Api/ScreensTest.php
tests/EventListener/RelationsChecksumListenerTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/2321
Fixed randomness issue in tests.

Fixed broken tests

---

CHANGELOG.md
composer.json
src/Command/LoadTemplateCommand.php

https://leantime.itkdev.dk/#/tickets/showTicket/3197
Added options to template command: set path to component and admin files from path to the json config file and option to add timestamp query parameter.

Added options to template command

---

CHANGELOG.md
composer.json
src/Command/LoadTemplateCommand.php

https://leantime.itkdev.dk/#/tickets/showTicket/3197
Added options to template command: set path to component and admin files from path to the json config file and option to add timestamp query parameter.

Added options to load template command

---

CHANGELOG.md
src/Feed/ColiboFeedType.php
src/Feed/SourceType/Colibo/ApiClient.php

https://leantime.itkdev.dk/#/tickets/showTicket/4260
Fixed issues with Colibo feed

Fixed issues with Colibo feed

---

assets/tests/template/template-vimeo.spec.js

https://leantime.itkdev.dk/?tab=timesheet#/tickets/showTicket/5317
Add test of vimeo, testing that the tag is rendered in the dom, and that the `src` attribute is sane

Add vimeo test

---

assets/tests/template/template-video.spec.js

https://leantime.itkdev.dk/?tab=timesheet#/tickets/showTicket/5317
Add test of video, testing that the tag is rendered in the dom, and that the `src` attribute is sane

Add video test

---

assets/admin/components/util/multi-and-table/select-slides-table.jsx
assets/admin/translations/da/common.json

https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=5276#/tickets/showTicket/5452
Add missing translation and use semantic html

5452: missing a trnaslation

---

assets/admin/components/playlist/shared-playlists-column.jsx
assets/admin/translations/da/common.json

https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=5276#/tickets/showTicket/5452
Fixed missing translations
Before: 
No after, it works

5452: fix missing translation

---

assets/tests/admin/admin-campaign.spec.js

https://leantime.itkdev.dk/#/tickets/showTicket/5317
Change from check of checkbox to click of list item.

5317 fix failing campaign test
