fixtures/playlist.yaml
fixtures/schedule.yaml
migrations/Version20211126082844.php
public/api-spec-v1.yaml
src/DataTransformer/PlaylistInputDataTransformer.php
src/DataTransformer/PlaylistOutputDataTransformer.php
src/Dto/Playlist.php
src/Dto/PlaylistInput.php
src/Entity/Playlist.php
src/Entity/Schedule.php
src/Repository/ScheduleRepository.php
tests/Api/PlaylistsTest.php

https://jira.itkdev.dk/browse/AR-692
- Changed playlist.schedule to playlist.schedules, which is an array of Schedule entities.

AR-692: Change playlist.schedule to an array of Schedule entities

---

src/Command/LoadScreenLayoutsCommand.php
src/Command/LoadTemplateCommand.php

https://jira.itkdev.dk/browse/AR-754
Moved `persist` call to after the `id`is set to avoid `missing an assigned ID` error
No screenshot

AR-754: Set id before calling persist

---

infrastructure/display-api-service/Dockerfile

https://jira.itkdev.dk/browse/AR-795
Composer 2 is copied to the wrong path in the `itkdev/php8.0-fpm:alpine` image. So the the composer:1 binary is not overwritten. 
No screenshot

AR-795: Fixed composer install path

---

.env
config/packages/cache.yaml
config/packages/lexik_jwt_authentication.yaml
docker-compose.server.yml
infrastructure/display-api-service/etc/confd/templates/env.local.tmpl

https://jira.itkdev.dk/browse/AR-799
Enables configuring token_ttl.
Changed screen login cache to 1 day default expire.

AR-769: Added option to set token ttl

---

config/packages/vich_uploader.yaml
config/services.yaml
fixtures/media.yaml
src/DataFixtures/Faker/Provider/MediaProvider.php
src/Service/MediaUploadTenantDirectoryNamer.php

https://jira.itkdev.dk/browse/AR-797
Added `MediaUploadTenantDirectoryNamer` to ensure uploaded files are stored tenant scoped directories

AR-797: Added MediaUploadTenantDirectoryNamer 

---

.env
.env.test
CHANGELOG.md
src/Entity/Interfaces/TenantScopedUserInterface.php
src/Entity/ScreenUser.php
src/Security/EventListener/JWTCreatedListener.php
tests/Api/AuthenticationScreenTest.php
tests/Api/AuthenticationUserTest.php

https://jira.itkdev.dk/browse/DISPLAY-969
* Fixed jwt ttl not set from config for ScreenUser
* Updated test suite to catch bug if it is re-introduced
* Set non-default TTL values for tests to ensure we test configured values and not default values.
N/A

DISPLAY-969: Fixed jwt ttl not set from config for ScreenUser

---

src/Feed/EventDatabaseApiFeedType.php

https://jira.itkdev.dk/browse/DISPLAY-947
Resolves
`"App\Feed\EventDatabaseApiFeedType::getConfigOptions(): Return value must be of type ?array, stdClass returned"`
N/A
N/A

DISPLAY-947: Fixed return type error

---

.github/workflows/php_upgrade.yaml
CHANGELOG.md

https://jira.itkdev.dk/browse/DISPLAY-1039
- [#160](https://github.com/os2display/display-api-service/pull/160)
Added app:feed:list-feed-source command. Removed listing from app:feed:remove-feed-source command.
- [#159](https://github.com/os2display/display-api-service/pull/159)
Fixed sprintf issue.
- [#158](https://github.com/os2display/display-api-service/pull/158)
Added thumbnails for image resources
N/A

DISPLAY-1039: Release 1.4.0

---

CHANGELOG.md
config/api_platform/playlist_slide.yaml
config/api_platform/screen_campaign.yaml
config/api_platform/screen_groups.yaml
config/api_platform/screen_groups_campaign.yaml
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Dto/Playlist.php
src/Dto/PlaylistSlide.php
src/Dto/Screen.php
src/Dto/ScreenCampaign.php
src/Dto/ScreenGroup.php
src/Dto/ScreenGroupCampaign.php
src/Dto/Slide.php
src/State/CampaignScreenGroupProvider.php
src/State/CampaignScreenProvider.php
src/State/FeedSourceProvider.php
src/State/MediaProvider.php
src/State/PlaylistProvider.php
src/State/PlaylistSlideProvider.php
src/State/ScreenCampaignProvider.php
src/State/ScreenGroupCampaignProvider.php
src/State/ScreenGroupProvider.php
src/State/ScreenGroupsScreensProvider.php
src/State/ScreenLayoutProvider.php
src/State/ScreenScreenGroupsProvider.php
src/State/SlidePlaylistProvider.php

https://jira.itkdev.dk/browse/DISPLAY-1088
- Adds `media` and `content` to slide serialization
- Expands objects in collections

Added media and content to slide serialization

---

CHANGELOG.md
src/DataFixtures/Loader/DoctrineOrmLoaderDecorator.php

https://leantime.itkdev.dk/tickets/showKanban?tab=ticketdetails#/tickets/showTicket/165
Disable RelationsModified listener when loading fixtures to optimize performance. Because the fixtures are loaded repeatedly when running the test suite this also improves the run time for the test suite.
```
$ time idc bin/phpunit --stop-on-failure
PHPUnit 9.6.13 by Sebastian Bergmann and contributors.
Testing 
................................................................. 65 / 96 ( 67%)
...............................                                   96 / 96 (100%)
Time: 03:48.111, Memory: 348.50 MB
```
```
$ time idc bin/phpunit
PHPUnit 9.6.13 by Sebastian Bergmann and contributors.
Testing 
................................................................. 65 / 96 ( 67%) …
```

#161: Disable RelationsModified listener when loading fixtures

---

CHANGELOG.md
src/Repository/PlaylistSlideRepository.php

https://jira.itkdev.dk/browse/SUPP0RT-1328
Fixed how playlists are added/removed from slides.

Bugfix: Attach playlists to slide bugs

---

CHANGELOG.md
migrations/Version20240405092445.php

https://leantime.itkdev.dk/#/tickets/showTicket/398
Add doctrine migration to change media references from API 'v1' to API 'v2' in slide content. Example:
```
{"images":["\/v1\/media\/01G1R1GWYWGBWNDK83AMGR3WAQ","\/v1\/media\/01G1R1GX31VBARESFZAMPJDWRF","\/v1\/media\/01G1R1GXAR4SBN4HT12PBH6XER"],"imageDuration":5}
{"images":["\/v2\/media\/01G1R1GWYWGBWNDK83AMGR3WAQ","\/v2\/media\/01G1R1GX31VBARESFZAMPJDWRF","\/v2\/media\/01G1R1GXAR4SBN4HT12PBH6XER"],"imageDuration":5}
```
If you have any further comments or questions for the …

398: Add doctrine migration to change media references from 'v1' to 'v2'

---

CHANGELOG.md
infrastructure/os2display/display-api-service/Dockerfile
infrastructure/os2display/display-api-service/docker-entrypoint.sh

N/A
Fixed parameter not set error in (os2display) api container
```
api-1        | /usr/local/bin/docker-entrypoint.sh: line 15: 1: parameter not set
api-1        | + /usr/local/bin/confd --onetime --backend env --confdir /etc/confd
```
See https://github.com/docker-library/php/issues/953

1456: Fixed "parameter not set" in api image

---

CHANGELOG.md
src/EventListener/RelationsChecksumListener.php

https://leantime.itkdev.dk/dashboard/show#/tickets/showTicket/2134
Running `app:screen-layouts:load` or `app:template:load` on large installations resulted in a SQL error
```
SQLSTATE[22003]: Numeric value out of range: 1916 Got overflow when converting '' to DECIMAL. Value truncated 
```
This happened in `App\EventListener\RelationsChecksumListener` because some of the resulting values from `GROUP_CONCAT()`resulted in strings to long to be valid integers. Thereby breaking on subsequent `=` comparisons.
Adding `DISTINCT` to `GROUP_CONCAT()` ensures this doesn't happen given that we are concatenating `0's` and `1's` . So with the `DISTINCT` the only possible results are `0`, `1`, `01`and `10`. Because the result of the `GROUP_CONCAT()` is only used as an `BOOLEAN`/ `TINYINT` this doesn't …

2134: Fixed sql error in relations modified listener

---

CHANGELOG.md
README.md
src/Controller/AuthOidcController.php

https://leantime.itkdev.dk/tickets/showKanban?tab=ticketdetails#/tickets/showTicket/2571
It should not be required to have a end session endpoint in openid connect setup.
As this is a one-off it is handled directly in this project rather than in our openid-connect bundle and library.
__NOTE__: Failing checks are fixed in https://github.com/os2display/display-api-service/pull/213 by updating symfony packages.

2571: Make endSessionUrl nullable

---

CHANGELOG.md
config/api_platform/feed_source.yaml
config/services.yaml
psalm-baseline.xml
public/api-spec-v2.json
public/api-spec-v2.yaml
src/Entity/Tenant/FeedSource.php
src/Feed/EventDatabaseApiFeedType.php
src/Feed/FeedTypeInterface.php
src/Feed/KobaFeedType.php
src/Feed/NotifiedFeedType.php
src/Feed/RssFeedType.php
src/Feed/SparkleIOFeedType.php
src/Repository/FeedSourceRepository.php
src/State/FeedSourceProcessor.php
src/State/FeedSourceSlideProvider.php
tests/Api/FeedSourceTest.php

[2829](https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/2829)
This PR introduces post, put and delete operations for the feed source endpoints. Furthermore it implements validation based on JSON schema.
N/A

2829: Feed source operations and data validation

---

CHANGELOG.md
docs/calender-api-feed.md
src/Feed/CalendarApiFeedType.php
tests/Feed/CalendarApiFeedTypeData.php
tests/Feed/CalendarApiFeedTypeTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/4021
* Added calendar api tests.
* Fixed bugs with modifiers.

Fixed issues with calendar api feed source modifiers

---

CHANGELOG.md
src/Feed/NotifiedFeedType.php

https://leantime.itkdev.dk/#/tickets/showTicket/3941
Fixed bug where no media url made Notified feed crash.

Notified Feed Type bug when media url is null

---

docs/test.md
scripts/test
scripts/test.sh

[4565](https://leantime.itkdev.dk/tickets/showKanban?showTicketModal=4565)
- Added documentation of bash script
- Added error handling and comments to bash script
- Added argument handling in bash script

Test documentation and bash script error handling

---

CHANGELOG.md
Taskfile.yml
composer.json

https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/5289
Taskfile added, somewhat copy pasted from [different](https://github.com/itk-dev/deltag.aarhus.dk/blob/develop/Taskfile.yml) [places](https://github.com/ai-platform-infrastructure/open-webui-docker/blob/main/Taskfile.yml)
🖼️

Added taskfile

---

README.md
assets/template/fixtures/slide-fixtures.js
assets/tests/template/template-travel.spec.js

https://leantime.itkdev.dk/?tab=timesheet#/tickets/showTicket/5317
Add test of travel template (rejseplanen)
- Add some fixtures to test that the information box takes up space
- Test that the iframe takes up space when there is no text configured
- Test that `monitorLayout` and `p1icons` are present in the iframe-url
- Remove file extension from readme

Travel template tests

---

assets/admin/components/screen/util/grid-generation-and-select.jsx
assets/admin/components/screen/util/grid.jsx

https://leantime.itkdev.dk/#/tickets/showTicket/4905
- Clean up grid generation a bit
🖼️

4905 clean up grid generation a bit

---

assets/template/fixtures/slide-fixtures.js
assets/tests/template/template-iframe.spec.js

https://leantime.itkdev.dk/?tab=ticketdetails#/tickets/showTicket/5317
Add iframe tests
🖼️

iframe template test
